# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4337f23b1d045c49e2e499082c0f73be02235e05ab4230af13c63e1805a57eeaee50d3f13067bb76466c9ab2c5753c25537725877ffd143b5e0112936071bc10

test:
  secret_key_base: 8ccbea9de9d1865972f1c6af17ac0aa366676181359c0438cab73a4bbd70435da06feb9a95a9789b2f29d43060a9626711e15de84b5cd185ab1e71956da3b955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
